apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: sftp-multitabelas-1
  namespace: processing
spec:
  arguments:
    - owner="SFTP_SAP"
    - table="TREINAMENTOS_120_DIAS"
    - chaves="MATRICULA,ID_ITEM ,Data_de_Conclusao_Historico_de_Treinamento,ID_da_turma_programada_Historico_de_treinamento"
    - path_origem="s3a://kafka/topics/src-sharepoint-rh-treinamentos-120-dias-avro/*/*.parquet"
  terminationGracePeriodSecond: 60
  timeToLiveSeconds: 60
  deps:
    pyFiles:
      - local:///opt/spark/work-dir/spark_session.py
      - local:///opt/spark/work-dir/functions_global.py
  sparkConf:
    spark.hadoop.fs.s3a.endpoint: "http://20.85.166.217"
    spark.hadoop.fs.s3a.access.key: "dG4x2vdz4wtp2rc0"
    spark.hadoop.fs.s3a.secret.key: "7PCTcAbDLHkOnzTeVZX2v20Lg8kBaaKc"
    spark.hadoop.fs.s3a.impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"
    spark.sql.extensions: "io.delta.sql.DeltaSparkSessionExtension"
    spark.sql.catalog.spark_catalog: "org.apache.spark.sql.delta.catalog.DeltaCatalog"
    spark.hadoop.fs.s3a.aws.credentials.provider: "org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider"
    spark.hadoop.fs.s3a.path.style.access: "True"
    spark.hadoop.fs.s3a.fast.upload: "True"
    spark.hadoop.fs.s3a.multipart.size: "104857600"
    spark.hadoop.fs.s3a.connection.maximum: "100"
  type: Python
  mode: cluster
  image: "luanb7/spark-3.2.3-delta:1.34"
  imagePullPolicy: IfNotPresent
  mainApplicationFile: "s3a://scripts/raw/nb_ingest_raw_trusted_list.py"
  sparkVersion: "3.2.3"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "2000m"
    memory: "1024m"
    serviceAccount: spark-operator-spark
  executor:
    cores: 1
    instances: 1
    memory: "1024m"
