apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: "delivery-data-from-sap-hana-to-kafka-{{ ds }}-{{ task_instance.try_number }}"
  namespace: processing
spec:
  type: Python
  mode: cluster
  image: "apache/spark-py:v3.4.0"
  imagePullPolicy: IfNotPresent
  mainApplicationFile: "s3a://scripts/ingest/delivery_data_from_sap_hana_to_kafka_py_spark.py"
  sparkVersion: "3.4.0"
  deps:
    packages:
      - org.postgresql:postgresql:42.7.1
      - com.sap.cloud.db.jdbc:ngdbc:2.19.15
      - com.oracle.database.jdbc:ojdbc8:23.3.0.23.09
      - org.apache.spark:spark-sql-kafka-0-10_2.13:3.4.0
      - com.amazonaws:aws-java-sdk-bundle:1.12.623
  terminationGracePeriodSecond: 60
  timeToLiveSeconds: 60
  restartPolicy:
    type: OnFailure
    onFailureRetries: 1
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  hadoopConf:
    fs.s3a.endpoint: "http://20.85.166.217"
    fs.s3a.impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"
    fs.s3a.path.style.access: "True"
    fs.s3a.connection.ssl.enabled: "false"
    fs.s3a.fast.upload: "true"
    fs.s3a.aws.credentials.provider: "com.amazonaws.auth.EnvironmentVariableCredentialsProvider"
  sparkConf:
    spark.delta.logStore.class: "org.apache.spark.sql.delta.storage.S3SingleDriverLogStore"
    spark.sql.extensions: "io.delta.sql.DeltaSparkSessionExtension"
    spark.sql.catalog.spark_catalog: "org.apache.spark.sql.delta.catalog.DeltaCatalog"
  driver:
    env:
      - name: AWS_ACCESS_KEY_ID
        value: dG4x2vdz4wtp2rc0
      - name: AWS_SECRET_ACCESS_KEY
        value: 7PCTcAbDLHkOnzTeVZX2v20Lg8kBaaKc
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.4.0
    serviceAccount: default
  executor:
    env:
      - name: AWS_ACCESS_KEY_ID
        value: dG4x2vdz4wtp2rc0
      - name: AWS_SECRET_ACCESS_KEY
        value: 7PCTcAbDLHkOnzTeVZX2v20Lg8kBaaKc
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.4.0
    serviceAccount: default