name: CI

on:
  pull_request:

permissions:
  id-token: write
  packages: write
  contents: write
  pull-requests: write
  attestations: write

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: ". --check --diff --config pyproject.toml"
      - name: Create Pull Request
        if: steps.action_black.outputs.is_formatted == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Format Python code with psf/black push"
          commit-message: ":art: Format Python code with psf/black"
          body: |
            There appear to be some python formatting errors in ${{ github.sha }}. This pull request
            uses the [psf/black](https://github.com/psf/black) formatter to fix these issues.
          base: ${{ github.head_ref }}
          branch: actions/black

  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: flake8 Lint
        uses: py-actions/flake8@v1
        with:
          args: "--config=.flake8"

  mypy:
    # or specify a path!
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: mypy check
        uses: jpetrucciani/mypy-check@master
        with:
          mypy_flags: "--config-file mypy.ini"

  tests:
    runs-on: ubuntu-latest
    needs: [black, flake8, mypy]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install poetry
        uses: abatilo/actions-poetry@v4
      - name: Setup a local virtual environment (if no poetry.toml file)
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
      - uses: actions/cache@v3
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Install the project dependencies
        run: poetry install
      - name: Run tests
        run: poetry run pytest -sxv

  adjust-imports:
    if: startsWith(github.head_ref, 'release')
    runs-on: ubuntu-latest
    needs: [black, flake8, tests]
    steps:
      - uses: actions/checkout@v4
      - run: find dags/ -type f -name '*.py' -exec sed -i 's/from dags./from /g' {} \; -ls
      # This step avoids a commit for each previous step and instead commits everything on a single commit
      - name: "Commit changes done in the previous steps"
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "refactor(bot): refactor files"
